--Grant permissions
REVOKE ALL ON SCHEMA public FROM PUBLIC;

GRANT ALL ON DATABASE adoptionapp TO larku;

-- GRANT ALL ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO larku;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE on ALL TABLES IN SCHEMA public TO larku;
GRANT USAGE, SELECT, UPDATE on ALL SEQUENCES IN SCHEMA public TO larku;

GRANT CONNECT ON DATABASE adoptionapp TO larku;

ALTER USER larku WITH SUPERUSER;